#!/usr/bin/env perl

use strict;

use File::Basename;
use SBG::Complex;
use SBG::STAMP;
use SBG::Role::Storable;

my ($fa, $fb) = @ARGV;

my $a = retrieve $fa;
my $b = retrieve $fb;
print STDERR "$fa :\n\t$a\n";
print STDERR "$fb :\n\t$b\n";

print $a->csuperpose($b, 1, 1), "\n";



