#!/usr/bin/env perl

use File::Basename;

use SBG::Model;
use SBG::Complex;
use SBG::DomainIO::stamp;
use SBG::Run::cofm qw/cofm/;

my $domfile = shift or exit;
my $base = basename($domfile, '.dom');

my $io = SBG::DomainIO::stamp->new(file=>$domfile);
my $complex = SBG::Complex->new;
while (my $dom = $io->read) {
    my $sphere = cofm($dom);    
    my $model = SBG::Model->new(query=>$dom, subject=>$sphere);
    $complex->set($dom, $model);
}

$complex->store("$base.stor");
exit;

