#!/usr/bin/env perl

use strict;

use File::Basename;
use SBG::NetworkIO qw(graphviz graphvizmulti);

################################################################################

my $templates = shift or die;
my $base = basename($templates, '.csv', '.dom');
my $gfile = $base . '-graph.dot';
my $mfile = $base . '-multi.dot';

# A L<Bio::Network::ProteinNet> of L<SBG::Interaction> templates
my $network = new SBG::NetworkIO(-file=>$templates)->read(1);

# Print input graph
graphviz($network, $gfile) and print "Graph: $gfile\n";
graphvizmulti($network, $mfile) and print "Multigraph: $mfile\n";

